# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 00:20
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('username', models.CharField(default=True, max_length=100, verbose_name='Nome completo')),
                ('telefone', models.CharField(default=True, max_length=15, verbose_name='Telefone')),
                ('cpf', models.CharField(default=True, max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(default=True, max_length=10, unique=True, verbose_name='RG')),
                ('dt_nasc', models.CharField(default=True, max_length=10, verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(default=True, max_length=1, verbose_name='Sexo')),
                ('rua', models.CharField(default=True, max_length=50, validators=[django.core.validators.RegexValidator(re.compile('[A-Za-z]', 32), 'A rua só deve conter letras.')], verbose_name='Rua')),
                ('numero', models.CharField(default=True, max_length=15, validators=[django.core.validators.RegexValidator(re.compile('[0-9]', 32), 'Favor digitar somente valores inteiros')], verbose_name='Número')),
                ('bairro', models.CharField(default=True, max_length=50, verbose_name='Bairro')),
                ('cidade', models.CharField(default=True, max_length=50, verbose_name='Cidade')),
                ('estado', models.CharField(default=True, max_length=50, verbose_name='Estado')),
                ('image', models.ImageField(blank=True, upload_to='accounts/images', verbose_name='Imagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='É da equipe?')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de entrada')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Usuários',
                'verbose_name': 'Usuário',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Chave')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmado?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name_plural': 'Novas Senhas',
                'verbose_name': 'Nova senha',
                'ordering': ['-created_at'],
            },
        ),
    ]
