# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(default=True, max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='user',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome completo'),
        ),
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.CharField(default=True, max_length=15, verbose_name='Telefone'),
        ),
    ]
