# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_rua'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numero',
            field=models.CharField(default=True, max_length=15, verbose_name='Número'),
        ),
    ]
