# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bairro',
            field=models.CharField(default=True, max_length=50, verbose_name='Bairro'),
        ),
    ]
