# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='estado',
            field=models.CharField(default=True, max_length=50, verbose_name='Estado'),
        ),
    ]
