# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20171023_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(default=True, max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
