# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20171023_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nome',
        ),
    ]
